version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12
    restart: always
    environment:
      DOCKER_HOST: npipe:////./pipe/docker_wsl
      POSTGRES_DB: sellThings
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgresql
    ports: 
      - 35000:5432